<?php

use Illuminate\Database\Seeder;
use Lio\Tags\Tag;

class TagSeeder extends Seeder
{
    public function run()
    {
        if (Tag::count() == 0) {
            $this->createTags();
        }
    }

    private function createTags()
    {
        $commonTags = [
            'ideas'                     => 'Ideas',
            'ideahub'                   => 'Idea Hub',
            'creativeideas'             => 'Creative Ideas',
            'entrepreneurship'          => 'Entrepreneurship',
            'entrepreneurshipproject'   => 'Entrepreneurship Project',
            'entrepreneurshipgoals'     => 'Entrepreneurship Goals',
            'entrepreneurstudents'      => 'Entrepreneur Students',
            'entrepreneurshiptrainings' => 'Entrepreneurship Trainings',
            'entrepreneurshipvillage'   => 'Entrepreneurship Village',
            'entrepreneurshiptip'       => 'Entrepreneurship Tip',
            'womenempowerment'          => 'Women Empowerment',
            'empowerment'               => 'Empowerment',
            'brandempowerment'          => 'Brand Empowerment',
            'careergoals'               => 'Career Goals',
            'productconsultancy'        => 'Product Consultancy',
            'consultancyadvice'         => 'Consultancy Advice',
            'freelancing'               => 'Freelancing',
            'upwork'                    => 'Upwork',
            'fiverr'                    => 'Fiverr',
            'pepoleperhour'             => 'Pepole Per Hour',
            'freelancer'                => 'Freelancer',
            '99designs'                 => '99designs',
            'guru'                      => 'Guru',
            'freelancingtips'           => 'Freelancing Tips',
            'freelancingguide'          => 'Freelancing Guide',
            'programming'               => 'Programming',
            'programmingproblems'       => 'Programming Problems',
            'programmingschool'         => 'Programming School',
            'programmingforkids'        => 'Programming For Kids',
            'programmingsucks'          => 'Programming Sucks',
            'c'                         => 'C',
            'cplusplus'                 => 'C Plus Plus',
            'java'                      => 'Java',
            'csharp'                    => 'C Sharp',
            'fsharp'                    => 'F Sharp',
            'jsharp'                    => 'J Sharp',
            'vb'                        => 'VB',
            'php'                       => 'PHP',
            'javascript'                => 'Javascript',
            'go'                        => 'Go',
            'r'                         => 'R',
            'python'                    => 'Python',
            'ruby'                      => 'Ruby',
            'android'                   => 'Android',
            'ios'                       => 'iOS',
            'androidwear'               => 'Android Wear',
            'applewatch'                => 'Apple Watch',
            'iosgames'                  => 'iOS Games',
            'androidgames'              => 'Android Games',
            'firebase'                  => 'Firebase',
            'uidesign'                  => 'UI Design',
            'webservices'               => 'Web Services',
            'xcode'                     => 'XCode',
            'eclipse'                   => 'Eclipse',
            'androidstudio'             => 'Android Studio',
            'androidlibs'               => 'Android Libs',
            'ioslibs'                   => 'iOS Libs',
            'rxreactive'                => 'Rx Reactive',
            'kotlan'                    => 'Kotlan',
            'ionic'                     => 'Ionic',
            'phonegap'                  => 'Phone Gap',
            'xamarin'                   => 'Xamarin',
            'html'                      => 'HTML',
            'html5'                     => 'HTML5',
            'css'                       => 'CSS',
            'css3'                      => 'CSS3',
            'jquery'                    => 'JQuery',
            'bootsrap'                  => 'Bootsrap',
            'materializecss'            => 'Materializecss',
            'zurbfoundation'            => 'Zurbs Foundation',
            'googlematerialdesignlte'   => 'Google Material Design LTE',
            'angular'                   => 'Angular',
            'react'                     => 'React',
            'backbonejs'                => 'Backbonejs',
            'ember'                     => 'Ember',
            'vuejs'                     => 'Vuejs',
            'yeoman'                    => 'Yeoman',
            'grunt'                     => 'Grunt',
            'gulp'                      => 'Gulp',
            'bower'                     => 'Bower',
            'laravel'                   => 'Laravel',
            'codeigniter'               => 'Codeigniter',
            'nodejs'                    => 'Nodejs',
            'zendframework'             => 'Zend Framework',
            'progressivewebapps'        => 'Progressive Web Apps',
            'rubyonrails'               => 'Ruby on Rails',
            'django'                    => 'Django',
            'wordpress'                 => 'Wordpress',
            'drupal'                    => 'Drupal',
            'joomla'                    => 'Joomla',
            'wix'                       => 'Wix',
            'relationaldatabases'       => 'Relational Databases',
            'distributeddatabases'      => 'Distributed Databases',
            'sql'                       => 'SQL',
            'nosql'                     => 'noSQL',
            'mysql'                     => 'MySQL',
            'sqlserver'                 => 'SQL Server',
            'oraclesql'                 => 'Oracle SQL',
            'mariadb'                   => 'Mariadb',
            'sqlite'                    => 'Sqlite',
            'postgresql'                => 'Postgre SQL',
            'mongodb'                   => 'Mongodb',
            'servermanagement'          => 'Server Management',
            'cpanel'                    => 'CPanel',
            'linuxserver'               => 'Linux',
            'ubuntuserver'              => 'Ubuntu',
            'centos'                    => 'CentOS',
            'debian'                    => 'Debian',
            'lampstack'                 => 'LAMP Stack',
            'htaccess'                  => 'htaccess',
            'azure'                     => 'Azure',
            'aws'                       => 'AWS',
            'digitaloceans'             => 'Digitaloceans',
            'linode'                    => 'Linode',
            'godaddy'                   => 'Godaddy',
            'github'                    => 'Github',
            'gitlab'                    => 'Gitlab',
            'bitbucket'                 => 'Bitbucket',
            'git'                       => 'Git',
            'trello'                    => 'Trello',
            'asana'                     => 'Asana',
            'redmine'                   => 'Redmine',
            'taskautomation'            => 'Task Automation',
            'deployment'                => 'Deployment',
            'security'                  => 'Security',
            'marketing'                 => 'Marketing',
            'seo'                       => 'SEO',
            'facebookmarketing'         => 'Facebook Marketing',
            'twitter'                   => 'Twitter',
            'instagram'                 => 'Instagram',
            'reddit'                    => 'Reddit',
            'google'                    => 'Google',
            'blogging'                  => 'Blogging',
            'nicheblogging'             => 'Niche Blogging',
            'quicksupport'              => 'Quick Support',
            'canva'                     => 'Canva',
            'adwords'                   => 'Adwords',
            'keywordplanner'            => 'Keyword Planner',
            'semrush'                   => 'SEM Rush',
            'yoast'                     => 'Yoast',
            'ppc'                       => 'PPC',
            'contentmarketing'          => 'Content Marketing',
            'prezi'                     => 'Prezi',
            'quora'                     => 'Quora',
            'wistia'                    => 'Wistia',
            'ask'                       => 'Ask',
            'disqus'                    => 'Disqus',
            'picmonkey'                 => 'Picmonkey',
            'pinterest'                 => 'Pinterest',
            'graphicdesigning'          => 'Graphic Designing',
            'adobephotoshop'            => 'Adobe Photoshop',
            'adobeillustrator'          => 'Adobe Illustrator',
            'adobemuse'                 => 'Adobe Muse',
            'adobexd'                   => 'Adobe xD (Experience Design)',
            'aftereffects'              => 'Adobe Aftereffects',
            'coreldraw'                 => 'CorelDraw',
            'cinema4d'                  => 'Cinema 4D',
        ];

        foreach ($commonTags as $name => $description) {
            Tag::create([
                'name' => $description,
                'slug' => $name,
                'description' => $description,
                'forum' => 1,
            ]);
        }
    }
}
